/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path = require("path");
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const WebpackBar = require("webpackbar");
const CircularDependencyPlugin = require("circular-dependency-plugin");
const WebpackProgress = require("../plugins/ChunkProgress/index");
const devEnv = require("../env/dev.env");

module.exports = require("./webpack.base.babel")({
  mode: "development",

  // Add hot reloading in development
  entry: [
    require.resolve("react-app-polyfill/ie11"),
    "webpack-hot-middleware/client?reload=true",
    path.join(process.cwd(), "src/main.tsx"), // Start with src/main.js
  ],

  // Don't use hashes in dev mode for better performance
  output: {
    filename: "[name].js",
    chunkFilename: "[name].chunk.js",
  },

  optimization: {
    splitChunks: {
      chunks: "all",
    },
  },

  // Add development plugins
  plugins: [
    new WebpackProgress(),
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: "public/index.html",
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false, // show a warning when there is a circular dependency
    }),
    new webpack.DefinePlugin({
      "process.env": devEnv,
    }),
    new WebpackBar(),
  ],
  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: "eval-source-map",
  performance: {
    hints: false,
  },
});
